events { }

http {
    upstream keycloak {
        server keycloak:8080;
    }

    upstream api {
        server api:8080;
    }

    server {
        listen 80;

        server_name keycloak.local;
        location / {
            proxy_pass http://keycloak;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;

        server_name caravan-api.local;
        location / {
            proxy_pass http://api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 443 ssl;
        server_name caravan-app.local;

        ssl_certificate     /etc/nginx/certs/cert.crt;
        ssl_certificate_key /etc/nginx/certs/key.key;

        root /usr/share/nginx/html;
        index index.html;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
